name: Build ISO

on:
  workflow_dispatch:

jobs:
  bluebuild-iso:
    name: Build ISO Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipes/recipe.yml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Image
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          push: true

      - name: Generate ISO
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          registry_token: ${{ github.token }}
          build_iso: true 
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NullVoidOS-ISO
          path: |
            ./*.iso
            ./*.sha256
